### ISSUE TITLE
Image not showing in the Teams Approval Card

### ISSUE THREAD

**Issue by grsandeep** [Hickey77/ccapproval#2]
We are unable to see the Image in the Teams Approval card. Tried with uploading the image in SP site and also tried using the image which is open to everyone

**Comment by Hickey77** [comment]
@grsandeep did you test the image the regular way (without the approval workflow)?  Images need to be max 1024x1024 per the adaptive card spec.  Also SPO is not supported, image location needs to be on public Internet without authentication. 

Good info here http://aka.ms/teamsbroadcasthub

**Comment by grsandeep** [comment]
Thanks Hickey, i tried with the public URL like https://i2.wp.com/sparrowsnews.com/wp-content/uploads/2020/12/wp-1608089416354.jpg which is also not coming in the Approval card
attached is the image of the Flow
![image](https://user-images.githubusercontent.com/28734783/116569944-7b287600-a927-11eb-8453-023f6d92ae70.png)

**Comment by Hickey77** [comment]
@grsandeep,  I gave it a shot with that image. 

The approval email cuts off the image for me:
![image](https://user-images.githubusercontent.com/54556057/116579308-41804c80-a8e0-11eb-8182-313ef67fb236.png)

The draft card in Communicator looks good though:
![image](https://user-images.githubusercontent.com/54556057/116579382-55c44980-a8e0-11eb-834a-3264c3c06835.png)

I messed around a bit trying to resize the image (to make it show better in Approval email).  Tried using the free Computer Vision API to resize.  Problem - Approvals don't support pictures - https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support

You could have the flow say "Click here to review image", which spawns a new window, but without picture markdown support in Approvals, we can't get it to render inline in the approval.
